name: Morning
on:
  schedule:
    - cron: '0 16 * * *'  # UTC时间16点=北京时间24点（原需求晚上8点需改为UTC 12点）
      timezone: Asia/Shanghai  # 显式声明时区[1](@ref)
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'  # 32位支持通过后续步骤实现[3](@ref)

      - name: Install 32-bit libraries
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y libc6:i386 zlib1g:i386

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt apscheduler==3.10.1  # 显式指定版本[7](@ref)

      - name: Run script
        run: python ./main.py
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
          USER_ID: ${{ secrets.USER_ID }}
          START_DATE: ${{ secrets.START_DATE }}
          BIRTHDAY: ${{ secrets.BIRTHDAY }}
          CITY: ${{ secrets.CITY }}
