name: Morning
on:
  schedule:
    - cron: '0 0 * * *'  # UTC时间0点（北京时间8点）
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install 32-bit libraries
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y libc6:i386 zlib1g:i386

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python ./main.py
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
          USER_ID: ${{ secrets.USER_ID }}
          START_DATE: ${{ secrets.START_DATE }}
          BIRTHDAY: ${{ secrets.BIRTHDAY }}
          CITY: ${{ secrets.CITY }}
